version: '2'
services:

### MySQL ###############################################
  mysql:
    image: mysql:5.7
    container_name: gics-2.8.6-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    labels:
      - "service-type:db-srv"
      - "environment:test"

### WildFly #############################################
  wildfly:
    image: mosaicgreifswald/wildfly:12.0.0-Final
    container_name: gics-2.8.6-wildfly
    links:
      - "mysql:mysqldb"
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      WILDFLY_PASS: wildfly_2018
    depends_on:
      - mysql
    volumes:
      - ./jboss:/entrypoint-jboss-batch
      - ./deployments:/entrypoint-deployments
    labels:
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 90 && ./run.sh"
